In [1]:
## Data Frame
# Two dimensional data structure
# Tabular way to represent data

# Create dataframe
import numpy as np
import pandas as pd

data = np.random.randn(5,3)
print(data)
print(type(data))
data_f = pd.DataFrame(data)   # Convert narray to DataFrame
print(data_f)
print(type(data_f))

[[ 1.24483866  1.15666152  0.64714658]
 [-1.26117988  0.71505456  0.54561034]
 [-1.76317168 -0.05277144  0.76669134]
 [ 1.04086948 -0.04610493 -0.38027827]
 [ 1.70566377  0.38774851  2.69641861]]
<class 'numpy.ndarray'>
          0         1         2
0  1.244839  1.156662  0.647147
1 -1.261180  0.715055  0.545610
2 -1.763172 -0.052771  0.766691
3  1.040869 -0.046105 -0.380278
4  1.705664  0.387749  2.696419
<class 'pandas.core.frame.DataFrame'>


In [2]:
# How to add headers to un-header dataset
data = np.random.randn(5,3)
print(data)
print(type(data))
data_f = pd.DataFrame(data, columns = ['A', 'B', 'C'])   # Convert narray to DataFrame
print(data_f)
print(type(data_f))

[[-0.64085385  0.06075602 -0.106707  ]
 [ 0.57848207  0.47982163 -0.69804526]
 [ 0.02961811 -1.143398   -0.46515698]
 [ 1.15809178  0.12863591 -0.71978195]
 [ 0.18813355 -0.1502812   1.02648389]]
<class 'numpy.ndarray'>
          A         B         C
0 -0.640854  0.060756 -0.106707
1  0.578482  0.479822 -0.698045
2  0.029618 -1.143398 -0.465157
3  1.158092  0.128636 -0.719782
4  0.188134 -0.150281  1.026484
<class 'pandas.core.frame.DataFrame'>


In [3]:
# Read dataset from csv
# But there is no header so please ignore header
# Also we are going to assign some custom header
# We can do that later after convert into DataFrame then use columns = []
# but we get this functionality in read_csv so why waste
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)
print(type(data_c))

<class 'pandas.core.frame.DataFrame'>


In [4]:
# Dataframe attribute
# Head
# It also create new dataFrame
print(data_c.head())    # 5 rows and 15 columns
print(data_c.tail())    # 5 rows and 15 columns

   age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0          2174             0              40   United-States   <=50

In [5]:
# Check index information
print(data_c.index)

RangeIndex(start=0, stop=32561, step=1)


In [6]:
# Check for values
print(data_c.values)

[[39 ' State-gov' 77516 ... 40 ' United-States' ' <=50K']
 [50 ' Self-emp-not-inc' 83311 ... 13 ' United-States' ' <=50K']
 [38 ' Private' 215646 ... 40 ' United-States' ' <=50K']
 ...
 [58 ' Private' 151910 ... 40 ' United-States' ' <=50K']
 [22 ' Private' 201490 ... 20 ' United-States' ' <=50K']
 [52 ' Self-emp-inc' 287927 ... 40 ' United-States' ' >50K']]


In [7]:
# Rows and Column
print(data_c.shape)

(32561, 15)


In [8]:
# Total values
print(data_c.size)

488415


In [9]:
# Find all columns
print(data_c.columns)

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'salary'],
      dtype='object')


In [10]:
# Data types of each column
print(data_c.dtypes)

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
salary            object
dtype: object


In [11]:
# Information regarding dataset
print(data_c.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    32561 non-null object
salary            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB
None


In [12]:
# Return statistical information regarding dataset only int and float type columns
print(data_c.describe())

                age        fnlwgt  education-num  capital-gain  capital-loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours-per-week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000  


In [13]:
# Add new ccolumn
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)
 
# Add new column : Age in month
data_c['Age in month'] =  data_c['age'] * 12
print(data_c.head(2))

   age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   

        marital-status        occupation    relationship    race    sex  \
0        Never-married      Adm-clerical   Not-in-family   White   Male   
1   Married-civ-spouse   Exec-managerial         Husband   White   Male   

   capital-gain  capital-loss  hours-per-week  native-country  salary  \
0          2174             0              40   United-States   <=50K   
1             0             0              13   United-States   <=50K   

   Age in month  
0           468  
1           600  


In [23]:
# Select more than one column
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)
data_c['Age in month'] =  data_c['age'] * 12

In [19]:
# Select single column
age_clm = data_c.age
age_clm

0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, Length: 32561, dtype: int64

In [24]:
data_c.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  \
0          2174             0              40   United-States   <=50K   
1             0             0              13   United-States   <=50K   
2             0             0              40   United-States   <=50K   
3             0             0              40   United-States   <=50K   
4             0             0              40            Cuba   <=50K   

   Age in month  
0           468  
1           600  
2           456  
3           636  
4           336

In [25]:
# This will when we have column name with space in it
last_clm = data_c['Age in month']
last_clm.head()

0    468
1    600
2    456
3    636
4    336
Name: Age in month, dtype: int64

In [26]:
# Select multiple column
mul_clm = data_c[['age','Age in month']]
mul_clm

age  Age in month
0       39           468
1       50           600
2       38           456
3       53           636
4       28           336
...    ...           ...
32556   27           324
32557   40           480
32558   58           696
32559   22           264
32560   52           624

[32561 rows x 2 columns]

In [27]:
# Broadcasting operation
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)
# add 5 to every element
print(data_c['age'] + 5)

0        44
1        55
2        43
3        58
4        33
         ..
32556    32
32557    45
32558    63
32559    27
32560    57
Name: age, Length: 32561, dtype: int64


In [34]:
# Drop missing rows or column 
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5],
                   [np.nan, np.nan, np.nan, np.nan]], columns = list('ABCD'))
# Here nan stands for missing values
# If we found any row with nan then discard it
df = df.dropna(axis = 0, how = 'any')   # zero record
df.head()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [33]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5],
                   [np.nan, np.nan, np.nan, np.nan]], columns = list('ABCD'))
df = df.dropna(axis = 0, how = 'all')     # 3 record
# Same goes to axis = 1
df.head()

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0

In [32]:
# Remove row and column
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5],
                   [np.nan, np.nan, np.nan, np.nan]], columns = list('ABCD'))
df = df.drop(axis = 0, labels = [2])
df = df.drop(axis = 1, columns = ['B'])
df.head()

A   C    D
0  NaN NaN  0.0
1  3.0 NaN  1.0
3  NaN NaN  NaN

In [35]:
# Filter data
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)

result_male = data_c['sex'] == ' Male'
# Return data where sex is Male only - Filtering done
cd = data_c['sex'] == ' Male'
data_n = data_c[cd]
data_n.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
7   52   Self-emp-not-inc  209642     HS-grad              9   

        marital-status          occupation    relationship    race    sex  \
0        Never-married        Adm-clerical   Not-in-family   White   Male   
1   Married-civ-spouse     Exec-managerial         Husband   White   Male   
2             Divorced   Handlers-cleaners   Not-in-family   White   Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black   Male   
7   Married-civ-spouse     Exec-managerial         Husband   White   Male   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
7             0             0              45   United-States    >50K

In [36]:
# Filtering data with multiple condition
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)
cd1 = data_c['sex'] == ' Male' 
cd2 = data_c['age'] > 50

res = data_c[cd1 & cd2]
res.head()

age          workclass  fnlwgt      education  education-num  \
3    53            Private  234721           11th              7   
7    52   Self-emp-not-inc  209642        HS-grad              9   
25   56          Local-gov  216851      Bachelors             13   
27   54                  ?  180211   Some-college             10   
41   53   Self-emp-not-inc   88506      Bachelors             13   

         marital-status          occupation relationship                 race  \
3    Married-civ-spouse   Handlers-cleaners      Husband                Black   
7    Married-civ-spouse     Exec-managerial      Husband                White   
25   Married-civ-spouse        Tech-support      Husband                White   
27   Married-civ-spouse                   ?      Husband   Asian-Pac-Islander   
41   Married-civ-spouse      Prof-specialty      Husband                White   

      sex  capital-gain  capital-loss  hours-per-week  native-country  salary  
3    Male             0             0              40   United-States   <=50K  
7    Male             0             0              45   United-States    >50K  
25   Male             0             0              40   United-States    >50K  
27   Male             0             0              60           South    >50K  
41   Male             0             0              40   United-States   <=50K

In [37]:
# Use .isin()
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)
cond1 = data_c['education'] == ' 11th'
cond2 = data_c['education'] == ' 12th'
cond3 = data_c['education'] == ' Masters'

In [38]:
temp = data_c[cond1 | cond2 | cond3]
# OR
temp1 = data_c['education'].isin([' 11th', ' 12th', ' Masters'])
result_or = data_c[temp1]
result_or.head()

age          workclass  fnlwgt education  education-num  \
3    53            Private  234721      11th              7   
5    37            Private  284582   Masters             14   
8    31            Private   45781   Masters             14   
18   38            Private   28887      11th              7   
19   43   Self-emp-not-inc  292175   Masters             14   

         marital-status          occupation    relationship    race      sex  \
3    Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
5    Married-civ-spouse     Exec-managerial            Wife   White   Female   
8         Never-married      Prof-specialty   Not-in-family   White   Female   
18   Married-civ-spouse               Sales         Husband   White     Male   
19             Divorced     Exec-managerial       Unmarried   White   Female   

    capital-gain  capital-loss  hours-per-week  native-country  salary  
3              0             0              40   United-States   <=50K  
5              0             0              40   United-States   <=50K  
8          14084             0              50   United-States    >50K  
18             0             0              50   United-States   <=50K  
19             0             0              45   United-States    >50K

In [39]:
# .between()
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)
re = data_c['age'].between(40, 60)
re = data_c[re]
re.head()

age          workclass  fnlwgt   education  education-num  \
1   50   Self-emp-not-inc   83311   Bachelors             13   
3   53            Private  234721        11th              7   
6   49            Private  160187         9th              5   
7   52   Self-emp-not-inc  209642     HS-grad              9   
9   42            Private  159449   Bachelors             13   

           marital-status          occupation    relationship    race  \
1      Married-civ-spouse     Exec-managerial         Husband   White   
3      Married-civ-spouse   Handlers-cleaners         Husband   Black   
6   Married-spouse-absent       Other-service   Not-in-family   Black   
7      Married-civ-spouse     Exec-managerial         Husband   White   
9      Married-civ-spouse     Exec-managerial         Husband   White   

       sex  capital-gain  capital-loss  hours-per-week  native-country  salary  
1     Male             0             0              13   United-States   <=50K  
3     Male             0             0              40   United-States   <=50K  
6   Female             0             0              16         Jamaica   <=50K  
7     Male             0             0              45   United-States    >50K  
9     Male          5178             0              40   United-States    >50K

In [40]:
# Find the unique element in column
re = data_c['sex'].unique()
len(re)
# Or
n = data_c['sex'].nunique()
n

2

In [41]:
# Sort_values
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)
data_c.sort_values(by = 'native-country')
data_c.sort_values(by = 'native-country', ascending = False)
data_c.sort_values(by = ['native-country', 'age'], ascending = False)

age          workclass  fnlwgt      education  education-num  \
13125   66            Private  142624     Assoc-acdm             12   
1025    56            Private  169133        HS-grad              9   
22200   56            Private  155657        7th-8th              4   
28487   45            Private  192323     Assoc-acdm             12   
29437   43            Private  557349           10th              6   
...    ...                ...     ...            ...            ...   
13603   18   Self-emp-not-inc  296090        HS-grad              9   
17481   18            Private  205894   Some-college             10   
30902   18            Private  174926            9th              5   
4396    17            Private  160118           12th              8   
27669   17            Private  113301           11th              7   

            marital-status          occupation    relationship    race  \
13125   Married-civ-spouse   Machine-op-inspct         Husband   White   
1025    Married-civ-spouse       Other-service         Husband   White   
22200             Divorced   Machine-op-inspct   Not-in-family   White   
28487   Married-civ-spouse        Craft-repair         Husband   White   
29437   Married-civ-spouse    Transport-moving         Husband   White   
...                    ...                 ...             ...     ...   
13603        Never-married               Sales       Own-child   White   
17481        Never-married               Sales       Own-child   White   
30902        Never-married       Other-service       Own-child   White   
4396         Never-married               Sales   Not-in-family   White   
27669        Never-married   Handlers-cleaners       Own-child   White   

           sex  capital-gain  capital-loss  hours-per-week native-country  \
13125     Male          5556             0              40     Yugoslavia   
1025      Male             0             0              50     Yugoslavia   
22200   Female             0             0              20     Yugoslavia   
28487     Male             0             0              66     Yugoslavia   
29437     Male             0             0              40     Yugoslavia   
...        ...           ...           ...             ...            ...   
13603     Male             0             0              48              ?   
17481     Male             0             0              25              ?   
30902     Male             0             0              15              ?   
4396    Female             0             0              10              ?   
27669     Male             0             0              12              ?   

       salary  
13125    >50K  
1025    <=50K  
22200   <=50K  
28487   <=50K  
29437   <=50K  
...       ...  
13603   <=50K  
17481   <=50K  
30902   <=50K  
4396    <=50K  
27669   <=50K  

[32561 rows x 15 columns]

In [43]:
# Sort index and inplace parameter
import pandas as pd
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)
# Suppose we performed some operation on dataset regarding shuffle
data_c.sort_values('native-country', inplace = True)
# Change back to original indexing
data_c.sort_index(inplace = True)
data_c.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [44]:
# .loc() and .iloc()
# Retrive individual rows from the dataframe
import pandas as pd
drink_data = pd.read_csv('drinks.csv')
# Change default indexing to one of the column
drink_data = pd.read_csv('drinks.csv', index_col = 'country')
drink_data.head()

beer_servings  spirit_servings  wine_servings  \
country                                                      
Afghanistan              0                0              0   
Albania                 89              132             54   
Algeria                 25                0             14   
Andorra                245              138            312   
Angola                 217               57             45   

             total_litres_of_pure_alcohol continent  
country                                              
Afghanistan                           0.0        AS  
Albania                               4.9        EU  
Algeria                               0.7        AF  
Andorra                              12.4        EU  
Angola                                5.9        AF

In [45]:
# Now index is country column
# .loc()
drink_data.loc['Albania']    # retrive row not column
# In normal retrive option withous loc we get column as result of retrival but when we want
# row as retrival output then go for loc
drink_data.loc['India']    # Series object
# I want to grab more than one rows at one shot
drink_data.loc[['Albania', 'India']]   # DataFrame
# Retrive specific column
drink_data.loc[['Albania', 'India']]['beer_servings']

# If we still want to use rows with number
drink_data.iloc[0]

beer_servings                    0
spirit_servings                  0
wine_servings                    0
total_litres_of_pure_alcohol     0
continent                       AS
Name: Afghanistan, dtype: object

In [46]:
# .astype()
import pandas as pd
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)
# Information regarding dtaset
data_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    32561 non-null object
salary            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [47]:
# In normal scenario pandas decide the suitable datatype for each column but sometimes
# it might affect the memory.
# for example : Most of the time gender is having two category that is male and female
# and sometimes pandas decide to give gender calumn as object as datatype which consumes
# higher memory as compare to category datatype
data_c['sex'] = data_c['sex'].astype('category')
data_c.info()   # Memory change to 3.7 to 3.5
# Same goes for merital status
data_c['marital-status'] = data_c['marital-status'].astype('category')
data_c.info()   # Memory change to 3.5 to 3.3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null category
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    32561 non-null object
salary            32561 non-null object
dtypes: category(1), int64(6), object(8)
memory usage: 3.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
educa

In [49]:
# set_index()
import pandas as pd
drink_data = pd.read_csv('drinks.csv')
# Change default indexing to one of the column
drink_data = pd.read_csv('drinks.csv', index_col = 'country')
# Or
data_drink = drink_data.set_index('continent')
data_drink.head()

beer_servings  spirit_servings  wine_servings  \
continent                                                  
AS                     0                0              0   
EU                    89              132             54   
AF                    25                0             14   
EU                   245              138            312   
AF                   217               57             45   

           total_litres_of_pure_alcohol  
continent                                
AS                                  0.0  
EU                                  4.9  
AF                                  0.7  
EU                                 12.4  
AF                                  5.9

In [50]:
# Apply method on multiple column
import pandas as pd
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)
data_c.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [51]:
def desc(row):
    age = row[0]
    sex = row[9]
    salary = row[14]
    temp = sex + ' earning ' + salary + ' $'
    return temp

data_c['result'] = data_c.apply(func = desc, axis = 'columns')
data_c.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  \
0          2174             0              40   United-States   <=50K   
1             0             0              13   United-States   <=50K   
2             0             0              40   United-States   <=50K   
3             0             0              40   United-States   <=50K   
4             0             0              40            Cuba   <=50K   

                     result  
0     Male earning  <=50K $  
1     Male earning  <=50K $  
2     Male earning  <=50K $  
3     Male earning  <=50K $  
4   Female earning  <=50K $

In [53]:
# Fetch random sample
import pandas as pd
names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',\
         'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',\
         'native-country', 'salary']
data_c = pd.read_csv('adult.csv', header = None, names = names)

m = data_c.sample(n = 1)
n = data_c.sample(frac = 1/100)
print(m)
print(n)
data_c.head()

     age          workclass  fnlwgt   education  education-num  \
891   35   Self-emp-not-inc  372525   Bachelors             13   

     marital-status        occupation    relationship    race    sex  \
891   Never-married   Exec-managerial   Not-in-family   White   Male   

     capital-gain  capital-loss  hours-per-week  native-country  salary  
891             0             0              40   United-States   <=50K  
       age workclass  fnlwgt      education  education-num  \
25955   24   Private  283092        HS-grad              9   
12862   37   Private  219546      Bachelors             13   
18226   45   Private  168038      Bachelors             13   
1530    47   Private  232628        HS-grad              9   
23175   46   Private   96080            9th              5   
...    ...       ...     ...            ...            ...   
28957   21         ?  509629   Some-college             10   
22521   50   Private  145409        HS-grad              9   
12280   24   Pri

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K